---
- name: Update Apache Web Root from Local Repository
  hosts: all
  become: yes
  vars:
    local_repo_path: "/path/to/your/local/your_repository"  # Update this path
    web_root_path: "/var/www/html"

  tasks:
    - name: Install Apache on Debian/Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Apache on Fedora/RedHat
      dnf:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Ensure Apache is running and enabled on boot
      systemd:
        name: "{{ 'apache2' if ansible_facts['os_family'] == 'Debian' else 'httpd' }}"
        state: started
        enabled: yes

    - name: Remove outdated web root contents
      ansible.builtin.file:
        path: "{{ web_root_path }}/"
        state: absent
      when: ansible_facts['distribution'] != 'RedHat'  # RedHat might require different handling

    - name: Recreate web root directory
      ansible.builtin.file:
        path: "{{ web_root_path }}"
        state: directory
        owner: "{{ 'www-data' if ansible_facts['os_family'] == 'Debian' else 'apache' }}"
        group: "{{ 'www-data' if ansible_facts['os_family'] == 'Debian' else 'apache' }}"
        mode: '0755'

    - name: Copy content to Apache web root
      ansible.builtin.copy:
        src: "{{ local_repo_path }}/"
        dest: "{{ web_root_path }}"
        remote_src: no
        owner: "{{ 'www-data' if ansible_facts['os_family'] == 'Debian' else 'apache' }}"
        group: "{{ 'www-data' if ansible_facts['os_family'] == 'Debian' else 'apache' }}"
        mode: '0644'

    - name: Restart Apache to apply changes
      systemd:
        name: "{{ 'apache2' if ansible_facts['os_family'] == 'Debian' else 'httpd' }}"
        state: restarted